'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { Session } from '@supabase/supabase-js';

type Creator={id:string;display_name:string;handle:string;city:string;bio:string;is_creator:boolean};
type Post={id:string;creator_id:string;caption:string;media_url:string|null;media_type:string;visibility:string;created_at:string};
type Report={id:string;reason:string;status:string|null;created_at:string;creator_id:string|null;post_id:string|null};
const demo=[
 {id:'d1',display_name:'LowKey Dre',handle:'lowkeydre',city:'West End',bio:'Streetwear fits and ATL drops.',is_creator:true},
 {id:'d2',display_name:'ATL Moe',handle:'atlmoe',city:'College Park',bio:'Everyday low-rise style.',is_creator:true},
 {id:'d3',display_name:'Jae Loose',handle:'jaeloose',city:'East Point',bio:'Fits, sneakers and city scenes.',is_creator:true},
];
const HANDLE_RE=/^[a-z0-9_]{3,24}$/;
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[msg,setMsg]=useState('');
 const [creators,setCreators]=useState<Creator[]>([]),[posts,setPosts]=useState<Post[]>([]),[selected,setSelected]=useState<Creator|null>(null);
 const [requestText,setRequestText]=useState(''),[budget,setBudget]=useState('20'),[caption,setCaption]=useState(''),[file,setFile]=useState<File|null>(null);
 const [isAdmin,setIsAdmin]=useState(false),[reports,setReports]=useState<Report[]>([]),[likes,setLikes]=useState<Set<string>>(new Set()),[follows,setFollows]=useState<Set<string>>(new Set());
 const [isCreator,setIsCreator]=useState(false),[pName,setPName]=useState(''),[pCity,setPCity]=useState(''),[pBio,setPBio]=useState(''),[pHandle,setPHandle]=useState('');
 const shown=useMemo(()=>creators.length?creators:demo,[creators]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadPrivate(data.session.user.id)});const {data:s}=supabase.auth.onAuthStateChange((_e,v)=>{setSession(v);if(v)loadPrivate(v.user.id)});load();return()=>s.subscription.unsubscribe()},[]);
 async function load(){
  const [{data:c},{data:p}]=await Promise.all([supabase.from('sfc_profiles').select('id,display_name,handle,city,bio,is_creator').eq('is_creator',true).limit(24),supabase.from('sfc_posts').select('*').eq('visibility','public').order('created_at',{ascending:false}).limit(30)]);
  setCreators((c||[]) as Creator[]);setPosts((p||[]) as Post[]);
 }

 async function loadPrivate(uid:string){
  const [{data:p},{data:l},{data:f}]=await Promise.all([supabase.from('sfc_profiles').select('is_admin,is_creator,display_name,handle,city,bio').eq('id',uid).single(),supabase.from('sfc_likes').select('post_id').eq('user_id',uid),supabase.from('sfc_follows').select('creator_id').eq('follower_id',uid)]);
  setIsAdmin(Boolean(p?.is_admin));setIsCreator(Boolean(p?.is_creator));
  setPName((p?.display_name as string)||'');setPCity((p?.city as string)||'');setPBio((p?.bio as string)||'');setPHandle((p?.handle as string)||'');
  setLikes(new Set((l||[]).map((x:{post_id:string})=>x.post_id)));setFollows(new Set((f||[]).map((x:{creator_id:string})=>x.creator_id)));
  if(p?.is_admin){const {data:r}=await supabase.from('sfc_reports').select('*').order('created_at',{ascending:false}).limit(50);setReports(r||[])}
 }
 async function toggleFollow(id:string){if(!session)return setMsg('Sign in to follow creators.');if(follows.has(id)){await supabase.from('sfc_follows').delete().eq('follower_id',session.user.id).eq('creator_id',id)}else{await supabase.from('sfc_follows').insert({follower_id:session.user.id,creator_id:id})}loadPrivate(session.user.id)}
 async function toggleLike(id:string){if(!session)return setMsg('Sign in to like posts.');if(likes.has(id)){await supabase.from('sfc_likes').delete().eq('user_id',session.user.id).eq('post_id',id)}else{await supabase.from('sfc_likes').insert({user_id:session.user.id,post_id:id})}loadPrivate(session.user.id)}
 async function resolveReport(id:string){const {error}=await supabase.from('sfc_reports').update({status:'resolved'}).eq('id',id);setMsg(error?error.message:'Report resolved.');if(session)loadPrivate(session.user.id)}
 async function auth(e:FormEvent){e.preventDefault();setMsg('Sending secure sign-in link...');const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname,data:{display_name:email.split('@')[0]}}});setMsg(error?error.message:'Check your email for the sign-in link.');}
 async function becomeCreator(){if(!session)return setMsg('Sign in first.');const handle=HANDLE_RE.test(pHandle)?pHandle:`creator_${session.user.id.slice(0,8)}`;const {error}=await supabase.from('sfc_profiles').update({is_creator:true,age_attested:true,handle}).eq('id',session.user.id);setMsg(error?error.message:'Creator mode enabled. 18+ attestation saved; identity/age verification remains pending. Complete your profile to power discovery.');load();if(session)loadPrivate(session.user.id)}
 async function saveProfile(){
  if(!session)return setMsg('Sign in first.');
  const name=pName.trim(),city=pCity.trim(),bio=pBio.trim(),handle=pHandle.trim().toLowerCase();
  if(!name||name.length>40)return setMsg('Display name is required (max 40 characters).');
  if(!HANDLE_RE.test(handle))return setMsg('Handle must be 3-24 characters: lowercase letters, numbers or underscores.');
  const {error}=await supabase.from('sfc_profiles').update({display_name:name,handle,city:city.slice(0,40),bio:bio.slice(0,200)}).eq('id',session.user.id);
  setMsg(error?error.message:'Profile saved. Your discovery card now shows your real name, city and bio.');
  load();loadPrivate(session.user.id);
 }
 async function sendRequest(){if(!session||!selected)return setMsg('Sign in and choose a creator first.');const cents=Math.round(Number(budget)*100);if(!requestText.trim()||cents<100)return setMsg('Add a request and at least $1 budget.');const {error}=await supabase.from('sfc_requests').insert({fan_id:session.user.id,creator_id:selected.id,request_text:requestText,budget_cents:cents});setMsg(error?error.message:'Request saved. Payment is not charged until processor approval.');if(!error){setRequestText('');setSelected(null)}}
 async function uploadPost(){
  if(!session||!file)return setMsg('Sign in as a creator and choose a file.');
  if(!isCreator)return setMsg('Enable creator mode first (step 1), then publish your drop.');
  if(!caption.trim())return setMsg('Add a caption so fans know what they are looking at.');
  const path=`${session.user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;setMsg('Uploading...');
  const {error:u}=await supabase.storage.from('sfc-media').upload(path,file);if(u)return setMsg(u.message);
  const {data}=await supabase.storage.from('sfc-media').getPublicUrl(path);
  const {error}=await supabase.from('sfc_posts').insert({creator_id:session.user.id,caption,media_url:data.publicUrl,media_type:file.type.startsWith('video')?'video':'image',visibility:'public'});
  setMsg(error?error.message:'Drop published — it is live in the public feed below. Share your profile to get your first custom requests.');
  if(!error){setCaption('');setFile(null);load()}
 }
 async function reportCreator(c:Creator){if(!session)return setMsg('Sign in to report.');const reason=prompt('Reason for report?');if(!reason)return;const {error}=await supabase.from('sfc_reports').insert({reporter_id:session.user.id,creator_id:c.id,reason});setMsg(error?error.message:'Report submitted for review.');}
 return <main className="min-h-screen bg-zinc-950 text-white"><section className="mx-auto max-w-6xl px-5 py-7">
  <nav className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-5"><div><p className="text-xs uppercase tracking-[.35em] text-lime-300">Atlanta creator culture</p><h1 className="text-2xl font-black">SAG FOR CASH</h1></div><div className="flex items-center gap-3 text-sm">{session?<><span className="hidden text-zinc-400 sm:inline">{session.user.email}</span><button onClick={()=>supabase.auth.signOut()} className="rounded-full border border-white/20 px-4 py-2">Log out</button></>:<span className="text-zinc-400">18+ only</span>}</div></nav>
  <section className="grid gap-8 py-12 md:grid-cols-[1.2fr_.8fr] md:items-start"><div><span className="rounded-full border border-lime-300/30 bg-lime-300/10 px-3 py-1 text-xs font-semibold text-lime-200">18+ CREATOR MARKETPLACE</span><h2 className="mt-5 text-5xl font-black leading-none md:text-7xl">Turn the look into a real creator hustle.</h2><p className="mt-5 max-w-2xl text-zinc-300">Profiles, public drops, premium-ready content, custom requests, reporting and creator tools built around streetwear culture.</p></div>
   <div className="rounded-3xl border border-white/10 bg-zinc-900 p-5">{!session?<form onSubmit={auth}><h3 className="text-xl font-black">Join or sign in</h3><p className="mt-2 text-sm text-zinc-400">Email magic-link login. You must be 18+.</p><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com" className="mt-4 w-full rounded-xl border border-white/10 bg-black px-4 py-3 outline-none"/><button className="mt-3 w-full rounded-xl bg-lime-300 px-4 py-3 font-black text-black">Send sign-in link</button></form>:<><h3 className="text-xl font-black">Creator onboarding</h3><p className="mt-1 text-xs uppercase tracking-[.25em] text-zinc-500">{isCreator?'Creator mode active':'3 steps to your first drop'}</p>
   {!isCreator&&<div className="mt-4 rounded-2xl border border-lime-300/20 bg-lime-300/5 p-4"><p className="text-sm font-bold text-lime-200">Step 1 — Enable creator mode</p><p className="mt-1 text-xs text-zinc-400">Confirms your 18+ attestation. Identity/age verification remains pending; no paid features are enabled.</p><button onClick={becomeCreator} className="mt-3 w-full rounded-xl border border-lime-300/40 px-4 py-3 font-bold text-lime-200">Enable creator mode + 18+ attestation</button></div>}
   {isCreator&&<>
   <div className="mt-4 rounded-2xl border border-white/10 bg-black/30 p-4"><p className="text-sm font-bold">Step 2 — Complete your profile</p><p className="mt-1 text-xs text-zinc-400">Your name, city, bio and handle power your discovery card.</p>
    <input value={pName} onChange={e=>setPName(e.target.value)} placeholder="Display name (required)" maxLength={40} className="mt-3 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/>
    <div className="mt-3 flex gap-3"><span className="text-zinc-500 self-center">@</span><input value={pHandle} onChange={e=>setPHandle(e.target.value)} placeholder="handle (a-z 0-9 _)" maxLength={24} className="w-full rounded-xl border border-white/10 bg-black px-4 py-3"/></div>
    <input value={pCity} onChange={e=>setPCity(e.target.value)} placeholder="City / neighborhood" maxLength={40} className="mt-3 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/>
    <textarea value={pBio} onChange={e=>setPBio(e.target.value)} placeholder="Short bio (what you post)" maxLength={200} className="mt-3 min-h-20 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/><button onClick={saveProfile} className="mt-3 w-full rounded-xl border border-white/20 px-4 py-2 font-bold">Save profile</button></div>
   <div className="mt-4 rounded-2xl border border-white/10 bg-black/30 p-4"><p className="text-sm font-bold">Step 3 — Publish your first drop</p><p className="mt-1 text-xs text-zinc-400">JPEG, PNG, WebP, MP4 or WebM. Public drops appear instantly in the feed.</p>
    <input value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Post caption" className="mt-3 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-3 w-full text-sm text-zinc-400"/><button onClick={uploadPost} className="mt-3 w-full rounded-xl bg-lime-300 px-4 py-3 font-black text-black">Publish public drop</button></div>
   </>}</>}</div></section>
  {msg&&<div className="mb-7 rounded-2xl border border-lime-300/20 bg-lime-300/5 p-4 text-sm text-lime-100">{msg}</div>}
  <section className="pb-12"><div className="mb-5"><p className="text-sm uppercase tracking-[.3em] text-zinc-400">Discover</p><h3 className="text-3xl font-black">Atlanta creators</h3></div><div className="grid gap-4 md:grid-cols-3">{shown.map(c=><article key={c.id} className="rounded-3xl border border-white/10 bg-zinc-900 p-5"><div className="aspect-square rounded-2xl bg-gradient-to-br from-zinc-800 to-zinc-700"/><h4 className="mt-4 text-xl font-black">{c.display_name}</h4><p className="text-sm text-zinc-400">@{c.handle} • {c.city}</p><p className="mt-2 min-h-10 text-sm text-zinc-300">{c.bio||'Creator profile'}</p><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setSelected(c)} className="rounded-xl bg-lime-300 px-3 py-2 text-sm font-bold text-black">Custom request</button><button onClick={()=>toggleFollow(c.id)} className="rounded-xl border border-white/10 px-3 py-2 text-sm">{follows.has(c.id)?'Following':'Follow'}</button><button onClick={()=>reportCreator(c)} className="col-span-2 rounded-xl border border-white/10 px-3 py-2 text-sm">Report</button></div></article>)}</div></section>
  <section className="pb-14"><div className="mb-5"><p className="text-sm uppercase tracking-[.3em] text-zinc-400">Feed</p><h3 className="text-3xl font-black">Public drops</h3></div>{posts.length?<div className="grid gap-4 md:grid-cols-3">{posts.map(p=><article key={p.id} className="overflow-hidden rounded-3xl border border-white/10 bg-zinc-900">{p.media_url&&(p.media_type==='video'?<video controls src={p.media_url} className="aspect-square w-full object-cover"/>:<img src={p.media_url} alt={p.caption||'Creator post'} className="aspect-square w-full object-cover"/>)}<div className="p-4"><p className="text-sm text-zinc-200">{p.caption||'New drop'}</p><div className="mt-3 flex items-center justify-between"><p className="text-xs uppercase tracking-wider text-zinc-500">Public • live backend</p><button onClick={()=>toggleLike(p.id)} className="rounded-lg border border-white/10 px-3 py-1 text-xs">{likes.has(p.id)?'♥ Liked':'♡ Like'}</button></div></div></article>)}</div>:<div className="rounded-3xl border border-dashed border-white/15 p-10 text-center text-zinc-500">No public uploads yet. The pipeline is live and waiting on the first creator post.</div>}</section>
  <section className="grid gap-4 pb-16 md:grid-cols-4">{[['Free feed','Public posts and creator discovery'],['Premium-ready','Schema supports locked content and pricing'],['Customs','Requests save securely before any charge'],['Safety','18+ gate, reporting, RLS and moderated media']].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h4 className="font-black">{a}</h4><p className="mt-2 text-sm text-zinc-400">{b}</p></div>)}</section>
  {isAdmin&&<section className="mb-14 rounded-3xl border border-amber-300/20 bg-amber-300/5 p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.3em] text-amber-200">Admin</p><h3 className="text-2xl font-black">Moderation queue</h3></div><span className="text-sm text-zinc-400">{reports.filter((r:Report)=>r.status!=='resolved').length} open</span></div><div className="mt-4 space-y-2">{reports.length?reports.map((r:Report)=><div key={r.id} className="flex flex-col gap-2 rounded-xl border border-white/10 bg-black/30 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm">{r.reason}</p><p className="text-xs text-zinc-500">{r.status||'open'} • {new Date(r.created_at).toLocaleString()}</p></div>{r.status!=='resolved'&&<button onClick={()=>resolveReport(r.id)} className="rounded-lg border border-amber-300/30 px-3 py-2 text-xs text-amber-100">Resolve</button>}</div>):<p className="text-sm text-zinc-500">No reports yet.</p>}</div></section>}
  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4"><div className="w-full max-w-lg rounded-3xl border border-white/10 bg-zinc-900 p-6"><div className="flex items-start justify-between"><div><p className="text-sm text-lime-300">CUSTOM REQUEST</p><h3 className="text-2xl font-black">{selected.display_name}</h3></div><button onClick={()=>setSelected(null)} className="text-zinc-400">✕</button></div><textarea value={requestText} onChange={e=>setRequestText(e.target.value)} placeholder="Describe the photo/video request. No illegal or sexual-service requests." className="mt-5 min-h-28 w-full rounded-xl border border-white/10 bg-black p-4"/><label className="mt-3 block text-sm text-zinc-400">Budget (USD)</label><input value={budget} onChange={e=>setBudget(e.target.value)} type="number" min="1" className="mt-1 w-full rounded-xl border border-white/10 bg-black px-4 py-3"/><button onClick={sendRequest} className="mt-4 w-full rounded-xl bg-lime-300 px-4 py-3 font-black text-black">Save request</button><p className="mt-3 text-xs text-zinc-500">No card is charged. Payments stay disabled until processor approval and compliance review are complete.</p></div></div>}
 </section></main>
}
